### ISSUE TITLE
linter

### ISSUE THREAD

**Issue by jouni-kantola** [davidxcheng/ruin#12]
We've already had discussions about code styles. Let's add a linter, instead of wasting time in the review process.

**Comment by davidxcheng** [comment]
Good call, jshint and immediatley caught a few mistakes. But we still need to agree on coding style⚔

**Comment by jouni-kantola** [comment]
Agree. I like this one:
https://github.com/airbnb/javascript

**Comment by jouni-kantola** [comment]
Added lint task in https://github.com/davidxcheng/ruin/pull/14.
